[package]
name = "mpcstark"
version = "0.1.1"
edition = "2021"

[dependencies]
mpc-stark = "0.2"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
futures = "0.3.28"
async-trait = "0.1.73"

